### ISSUE TITLE
Factory failure drains available connection max from pool

### ISSUE THREAD

**Issue by randall-fulton** [buraksezer/connpool#4]
# Issue

If the provided `factory` returns an error, the pool's total connection limit will permanently decrease by one. Provided this happens enough times, the pool can become deadlocked, with zero capacity.

Here is a playground example of the issue: https://go.dev/play/p/lAy0_uoKMFj

Notice after the first two failures (the number of max connections in the pool) the errors change, due to the pool itself never being able to attempt to fetch new connections.

# Expected Outcome

When the `factory` fails, the reserved slot in the pool should be returned to the pool.

**Comment by randall-fulton** [comment]
Working on a fix for this now.

**Comment by buraksezer** [comment]
Thank you for your contribution @randall-fulton
